### ISSUE TITLE
Trying to set up Kandan

### ISSUE THREAD

**Issue by benkoshy** [DamageLabs/kandan#451]
Hi guys

I'm wanting to help with development. But before I do anything I want to see what Kandan is currently doing, how it works etc.

I am working on Ubuntu. I want to set it up on this pc, on development environment is fine. something quick and dirty so i can see what's going on. I'm currently on rails 4. I followed the instructions given here to a T: https://github.com/kandanapp/kandan/blob/master/DEPLOY.md#standalone-server

but have received this dump when i tried to run bundle install:

does anybody have any idea of what is going on or what it means?

regards

Ben

`rails s
/home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`require': cannot load such file -- guard/guard (LoadError)
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/guard-spork-1.5.1/lib/guard/spork.rb:2:in`<top (required)>'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in`rescue in block in require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`each'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in`require'
    from /home/koshy/Documents/coding/rails_apps/kandan/config/application.rb:13:in `<top (required)>'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:53:in`require'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in`tap'
    from /home/koshy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'
`

Could this be the solution (from google)? I thought maybe someone would know the answer easily before I spend the next hour or two trying to get it working:

`1) Just remove guard-spring from your Gemfile and Guardfile.
2) Then upgrade guard-rspec (run bundle update guard-rspec)
3) Setup guard-rspec to use spring (see this: https://github.com/guard/guard-rspec#options)

Explanation:
guard-spring is not updated to work with newer versions of Guard, but it's not even necessary anymore, since guard-rspec supports spring.`

**Comment by mzch** [comment]
I had the same issue. Try to use ruby 2.0.0. It works.

**Comment by fusion94** [comment]
Closing as part of Kandan revival project. The app is being rebuilt from scratch on a modern stack (Angular + Express/Node). See the upcoming kandan-core repository for the new version.
